### PR TITLE
Make the mode for the chef-client log an attribute

### PR DESCRIPTION
**Pull request by jcookfastrobot**
We need to make our chef-client log (/var/chef/log/client.log) readable by folks other than root.
I noticed that the mode for the log_file was hardcoded to '00640', which is good for security, but bad for our users without sudo access.

I have made the mode an attribute that can be overridden in a wrapper cookbook.
Optimistically, I have updated the docs to mention the new attribute and set the default to '00640' as well.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by jtimberman** [comment]
As I said in #274 and #257, I'm pretty strongly against adding more attributes to this cookbook. I'd really like to clean up and refactor a lot of the things that we're doing in this cookbook, per #282.

In #257, we opted to make the log directory mode `0755`. We didn't make the log file itself `0644` though. As you point out that's potentially bad for security because depending on what you're doing on the system in Chef, the log file might have sensitive information displayed. As long as we're clear about that in the documentation for this cookbook, then I think just setting it to `0644` is fine.

**Comment by cullenmcdermott** [comment]
+1 I'd like this as well. I opened #316 without realizing this was here.

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by tas50** [comment]
This has been merged via another PR

**Pull request closed without merging**
