### PR TITLE
support for controlling cron mode with an init_style attribute

### PR DESCRIPTION
**Pull request by prein**
### Description

Currently I am able to control the way I run chef-client as a service with "init_style" attribute, while having only "default" recipe in the run_list. I would like to achieve the same, consistent style of control for running chef-client using cron, with "init_style" set to "cron" (although naming... technically cron does not have to do with init). 

Example use case: Imagine one is switching from running chef-client as a service to running it as cron job and he would like to experiment in one of environments first without having to manipulate run lists. 
### Issues Resolved

none
### Check List
- [ ] All tests pass. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD
- [ ] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] The CLA has been signed. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @prein
* @acasimirosmart

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by josephholsten** [comment]
@prein did you want us to be able to merge this PR? It seems reasonable, but we can't if you don't legally permit us to by signing the CLA.

**Comment by prein** [comment]
@josephholsten I have signed the CLA, twice actually, some years ago, does it expire? I never was an active contributor, which is a shame, but have the agreement signed. On a sentimental note I am proud for my name to be found on approved contributors list back in 2010 (https://web.archive.org/web/20100825175929/http://wiki.opscode.com/display/chef/Approved+Contributors) :)

**Comment by dheerajd-msys** [comment]
@prein Please check ^

**Comment by tas50** [comment]
Now that we have a cron resource I'm going to close this out since users can add any number of cron jobs for chef-client to their recipes.

**Pull request closed without merging**
