### PR TITLE
make sure node[chef_client][cron][nice_path] is used everywhere

### PR DESCRIPTION
**Pull request by scalp42**
sorry @tas50, missed another cron_d resource

### CODE REVIEW

**Comment by tas50** [comment]
@scalp42 can you sign this commit for the DCO?

**Comment by scalp42** [comment]
all set @tas50

**Comment by dheerajd-msys** [comment]
@scalp42 Travis failed, Could you please try a fresh push so as to get it passed.

Thanks!!

**Comment by tas50** [comment]
Thanks @scalp42

**Pull request merged**
