### PR TITLE
Stop chef-client windows service after creating scheduled task

### PR DESCRIPTION
**Pull request by jasonwbarnett**
### Description

Along with disabling the service from stopping we should actually stop the windows chef-client service.

### Issues Resolved

N/A

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by jasonwbarnett** [comment]
@tas50 does this make sense? It seemed odd that there wasn't parity between the linux cron recipe and this one. Thoughts?

**Comment by tas50** [comment]
I think you're going to run into some nasty issues here where the chef-client laying this down is the one trying to stop itself. This order *might* make that work, but any chance you can test that somehow?

**Comment by jasonwbarnett** [comment]
Yeah, it throws a `Timeout::Error`, ugh. I wish we could somehow stop the service cleanly. Let me play with this a bit and I'll get back to you.

**Comment by jasonwbarnett** [comment]
The only thing I can think to do to "trick" chef into stopping chef from the scheduled task is to do something like,

```ruby
windows_service 'chef-client' do
  action :stop

  only_if { ::File.exist?('c:/chef/.stop_chef') }
end

file 'c:/chef/.stop_chef'
```

**Comment by jasonwbarnett** [comment]
You know... we could always just use the `ignore_failure true` on the service stop.

**Comment by jasonwbarnett** [comment]
@tas50 
yikes... was this ready?

**Pull request merged**
