### PR TITLE
Allow cmd arguments in cron definition

### PR DESCRIPTION
**Pull request by Igorshp**
Ran into an issue where I need to run chef-client on cron but with specific command line arguments.
Unfortunately there doesn't seem to be a way of doing this currently.

Here's the end result i'm after:

`/usr/bin/chef-client --audit-mode audit_only`

This PR allows us to add custom params to the end of the chef-client.

### CODE REVIEW

**Comment by tas50** [comment]
@Igorshp If you're still interested in this can you rebase this change against the current state of the cookbook and remove the version bump since we have tooling. Also you'll want to document this change in the readme so other users can find out about it.

**Comment by dheerajd-msys** [comment]
@Igorshp Please check ^

**Comment by Igorshp** [comment]
Thanks, let me take a look

**Comment by tas50** [comment]
Closing this out since we actually allow arbitrary arguments now.

**Pull request closed without merging**
