### PR TITLE
Add support for daemon options in the windows task

### LINKED ISSUE #356: Add daemon specific options for windows
Hello,

i would like to have the possibility to set an attribute similar ( or use the same)  to node['chef_client']['daemon_options'] for windows tasks.

Thanks

### PR DESCRIPTION
**Pull request by drrk**
Refactor the build of the command line for creating the windows scheduled task,
and add in daemon options array, as with the cron recipe.

Fixes #356

### CODE REVIEW

**Comment by drrk** [comment]
It would be useful if someone could check this on a windows system themselves, I have checked, but there are no automated tests for windows sadly.

**Comment by tas50** [comment]
@chef-cookbooks/client-windows Any thoughts on this?

**Comment by mwrock** [comment]
Looks like it should work but would be cool to add a kitchen test or two to validate.

**Comment by drrk** [comment]
@mwrock I have tested it manually, but currently there is no windows testing in the kitchen setup at all.

**Comment by mwrock** [comment]
Heh I was confused and thought this was the windows cookbook where there are kitchen tests in appveyor.

I'm :+1: here

**Comment by tas50** [comment]
@drrk Can you rebase this for the changes to windows task that @mwrock just made?  I'll get it merged in after that.

**Comment by tas50** [comment]
ping @drrk on the rebase

**Comment by drrk** [comment]
I've rebased - not run the manual check yet, as I am in the back of a Taxi to the airport, but it should be the same - the test is to bring up a windows machine, run the recipe with an additional option in daemon_options and then check the scheduled tasks manually on the machine.

**Pull request merged**
