### PR TITLE
fix systemd timer activation

### LINKED ISSUE #613: OnActiveSec is the wrong timer property for triggering the service unit on an interval
### Cookbook version
11.0.5

### Chef-client version
14.9.13

### Platform Details
CentOS 7.6.1810

### Scenario:
systemd timer unit triggered activation of chef-client.service

### Steps to Reproduce:
set up the timer/service units as the cookbook currently does 

e.g.
```
PRODUCTION [root@bastion.prod.iad01.treehouse chef-client]$ cat /etc/systemd/system/chef-client.timer
[Unit]
Description = chef-client periodic run

[Install]
WantedBy = timers.target

[Timer]
OnBootSec = 1min
OnActiveSec = 1800sec
RandomizedDelaySec = 900sec
PRODUCTION [root@bastion.prod.iad01.treehouse chef-client]$ cat /etc/systemd/system/chef-client.service 
[Unit]
Description = Chef Client daemon
After = network.target auditd.service

[Service]
Type = oneshot
EnvironmentFile = /etc/sysconfig/chef-client
ExecStart = /usr/bin/chef-client -c $CONFIG $OPTIONS
ExecReload = /bin/kill -HUP $MAINPID
SuccessExitStatus = 3

[Install]
WantedBy = multi-user.target
```

start the timer, wait for service unit to be activated at the $interval mark. service unit will not be activated once $interval has elapsed unless the timer unit is restarted during the chef converge.

you can see from `systemctl list-timers` output whether it will work in the future, an n/a for "LEFT" or "NEXT" means it will not be triggered.

### Expected Result:
service unit is activated every $interval, not just once after $interval from timer unit starting

### Actual Result:
service unit is only activated once after timer unit is activated

### PR DESCRIPTION
**Pull request by nathwill**
### Description

makes timer based activation work again

### Issues Resolved

#613 #557 

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by nathwill** [comment]
pushing this to our cluster as a hot-fix to get our nodes converging again, will report back.

**Comment by nathwill** [comment]
verified this is working in our cluster; testing this in kitchen is a little more complicated... poking around at unit properties to see if there's a way to verify that the timer has triggered and has an upcoming trigger time

**Comment by nathwill** [comment]
ok, so we can check NextElapseUSec properties for verifying that a sd-event has been scheduled and the timer isn't going to be idle indefinitely: https://github.com/systemd/systemd/blob/2d479ff1cc045eae971687ee770720fc444dee37/src/core/timer.c#L39

we can also check LastTriggerUSec properties to see if the timer has triggered, but there's a race between the OnBootSec and the integration tests running that is usually won by the integration tests, so without inserting a sleep longer than OnBootSec we can't really verify that NextElapseUSec has been calculated after the OnBootSec trigger has been applied (i.e. based on OnUnitInactiveSec). at the point where we're inserting sleeps into the tests, i'm inclined to say it's not worth it, but in this case, this has actually been an issue for some users, so... :man_shrugging: thoughts?

**Comment by nathwill** [comment]
well, at least these tests are better than nothing. unfortunately it looks like it's pretty tough to reliably get information about trigger timing beyond the initial one, so leaving that out for now.

**Comment by voroniys** [comment]
I'm having the issue as well. Please include this fix ASAP, since current implementation is incorrect!

**Comment by tas50** [comment]
Sorry for the delay on this one @nathwill and thanks for the tests

**Pull request merged**
